import uuid from 'uuid/v1';

export default [
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '이국종',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_01.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '김경희',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_02.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '3',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_03.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '4',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_04.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '5',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_05.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '6',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_Default.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '7',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_Default.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '8',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_Default.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '9',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_Default.jpg',
    createdAt: 1555016400000
  },
  {
    id: uuid(),
    doctorNo : '1',
    doctorName: '10',
    age : '51',
    position: '센터장',
    detailData : ['외과', '외상외과', '응급구조학과'],
    specialized : '대통령 표창장 수상',
    medicalSubject: ['외과', '외상외과'],
    hospitalNo : '1',
    avatarUrl: '/admin_images/avatars/Doctor_Default.jpg',
    createdAt: 1555016400000
  },
];
